####################################################
### Read documentation before updating this file ###
###    Add DOCUMENTATION LINK HERE
####################################################

name: New Feature
description: Issue for new feature
title: "feat: [ADD TITLE HERE]"
labels: ["feature", "enhancement"]
projects: ["AliveOrganization/2"]
body:
  - type: markdown
    attributes:
      value: |
        Je suis pas sexiste
  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      placeholder: Should do this when I click here...
    validations:
      required: true
