####################################################
### Read documentation before updating this file ###
###    Add DOCUMENTATION LINK HERE
####################################################

name: New Refactor
description: Code/Design update without added functionality or performance improvements.
title: "refactor: [ADD TITLE HERE]"
labels: ["code update"]
projects: ["AliveOrganization/2"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the update
      placeholder: Actually is like this and should be like this...
    validations:
      required: true
