####################################################
### Read documentation before updating this file ###
###    Add DOCUMENTATION LINK HERE 
####################################################

name: New Classic Task
description: Issue for new classic task
title: "task: [ADD TITLE HERE]"
labels: ["task"]
projects: ["AliveOrganization/2"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the task
    validations:
      required: true